var fso = new ActiveXObject("Scripting.FileSystemObject");

var inputPath = "..\\..\\source\\jq\\state.jq";
var outputPath = "..\\..\\source\\jq\\minified.mc";
var variableName = "EVCC_JQ_FILTER";

var file = fso.OpenTextFile(inputPath, 1);
var text = file.ReadAll();
file.Close();

// Remove full-line jq comments before removing line breaks.
text = text.replace(/^\s*#.*$/gm, "");

// Replace line breaks with spaces.
text = text.replace(/[\r\n]+/g, " ");

// Collapse repeated whitespace.
text = text.replace(/\s+/g, " ").replace(/^\s+|\s+$/g, "");

// Escape for Monkey C string.
text = text.replace(/\\/g, "\\\\");
text = text.replace(/"/g, '\\"');

var out = fso.CreateTextFile(outputPath, true);
out.WriteLine("// This file is automatically generated from state.jq. Do not edit manually. Use ./scripts/generate-jq.bat to regenerate it.");
out.WriteLine('const ' + variableName + ' = "' + text + '";');
out.Close();